In [140]:

from sklearn.base import TransformerMixin, BaseEstimator

from collections import Counter , defaultdict

import pandas as pd

pd.set_option('display.max_columns', None)


from pandas import Series as s , DataFrame as df
import numpy as np

import seaborn as sns
# import matplotlib.pyplot as plt

# To ignore warnings
import warnings
warnings.filterwarnings("ignore")

from matplotlib import pyplot as plt, rcParams as rc


%matplotlib inline
rc["figure.figsize"] = 10,6

import datetime
import datetime as dt

from sklearn.model_selection  import StratifiedKFold
from sklearn.decomposition import PCA

from iteration_utilities import duplicates, unique_everseen

import sys
from itertools import groupby
from operator import itemgetter
from timeit import timeit


## RandomOverSampler to handle imbalanced data
from imblearn.over_sampling import RandomOverSampler # over sampling method 2

Using TensorFlow backend.


In [52]:

#Algorithm
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.naive_bayes import MultinomialNB

from lightgbm import LGBMClassifier
# from catboost import CatBoostClassifier

#preprocessing
from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import StandardScaler, normalize



from sklearn.model_selection import train_test_split

import lightgbm as lgb


#Metrics
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, recall_score, precision_score
from sklearn.metrics import confusion_matrix, classification_report, f1_score, precision_recall_fscore_support

from sklearn.pipeline import Pipeline

# GridSearchCV to find optimal min_samples_leaf
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [53]:
df = pd.read_csv("train_Wc8LBpr.csv")

df_test = pd.read_csv("test_VsU9xXK.csv")
submission = pd.read_csv("sample_submission_NoPBkjr.csv")

df10 = df.copy()
df.shape, df_test.shape, submission.shape

((131662, 14), (87395, 13), (87395, 2))

In [54]:
def get_percentage_miss_value(dataset):
    higher_miss_value_column = []
    miss_threshold_value = 50
    
    for i in dataset.columns:
        if dataset[i].isna().sum() > 1: 
            perectange_val = (dataset[i].isna().sum() / len(dataset)) * 100
            print("Column-> " , i, ", total no of missing value : ",dataset[i].isna().sum() , " & :         ", round(perectange_val,2) ," %")
                
            if(perectange_val > miss_threshold_value):
                higher_miss_value_column.append(i)
            
    print("\n\n\n")
    
    if higher_miss_value_column:
        print("Higher Missing values in Columns for Delete : ", higher_miss_value_column)
    else:
        print("There are no Higher Column Missing values in Dataset")

In [55]:
# get_percentage_miss_value(df)

In [56]:
# get_percentage_miss_value(df_test)

In [57]:
# df.info()

In [58]:
def check_cloumn_details_type_categorical(dataset):
    for i in dataset.columns:
        if(dataset[i].dtype == "object"):
            print("Columns name :  ",i  )
            
            print(dict(Counter(dataset[i])))
            
            print("*"*100)
            print("\n")

In [59]:
# check_cloumn_details_type_categorical(df)

In [60]:
93900 / len(df)

0.7131898345764154

In [61]:
# check_cloumn_details_type_categorical(df_test)

In [62]:
def check_cloumn_details_type_numberical(dataset):
    for i in dataset.columns:
        if (dataset[i].dtype == "int"):
            print("Columns name :  ",i  )
            
            print(dict(Counter(dataset[i])))
            print("*"*100)
            print("\n")
            
            
def check_cloumn_details_type_float(dataset):
    for i in dataset.columns:
        if (dataset[i].dtype == "float"):
            print("Columns name :  ",i  )
            
            print(dict(Counter(dataset[i])))
            print("*"*100)
            print("\n")
            

In [63]:
# check_cloumn_details_type_numberical(df)

In [64]:
# check_cloumn_details_type_float(df)

In [65]:
# Visulazing the distibution of the data for every feature
def visualize_hist(dataset):
    dataset.hist(edgecolor='black', linewidth=1.2, figsize=(20, 20));
    plt.show()

In [66]:
# visualize_hist(df)

In [67]:
def visualize_histogram(dataset):
    # plot histogram
    plt.figure(figsize=(25, 9))  # figure size in ratio 16:9
    features = dataset.columns  # list of columns name
    for i, j in enumerate(features):
        plt.subplot(3, 3, i + 1)  # create subplot for histogram
        plt.title("Histogram of {}".format(j), fontsize=15)  # title of histogram

        bins = len(dataset[j].unique())  # bins for histogram
        plt.hist(dataset[j], bins=bins, rwidth=0.8, edgecolor="y", linewidth=2, )  # plot histogram

    plt.subplots_adjust(hspace=0.5)  # space between horixontal axes (subplots)

In [68]:
# visualize_histogram(df)

In [69]:

    
def corr_metrix(dataset):
    corr = dataset.corr()
    # Generate a mask for the upper triangle
    mask = np.zeros_like(corr, dtype=np.bool)
    mask[np.triu_indices_from(mask)] = True

    # Set up the matplotlib figure
    f, ax = plt.subplots(figsize=(11, 9))

    # Generate a custom diverging colormap
    cmap = sns.diverging_palette(220, 10, as_cmap='RdYlGn')

    # Draw the heatmap with the mask and correct aspect ratio
    sns.heatmap(corr, mask=mask, cmap=cmap, vmax=1, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5});
    ax.tick_params(labelsize=20)

def corr_2_more_visualize(dataset):
    corr = dataset.corr()
    
    f, ax = plt.subplots(figsize=(20, 9))
    sns.heatmap(corr.apply(lambda x : np.round(x,2)), 
            xticklabels=corr.columns.values,
            yticklabels=corr.columns.values,annot=True,cmap='RdYlGn', annot_kws={"size": 15})
    ax.tick_params(labelsize=20)
    plt.show()
    
    
def linear_regression_train_test():
    #Linear regression with L2 regularization
    for i in range(-2, 3):
        alpha = 10**i
        rm = Ridge(alpha = alpha)
        ridge_model = rm.fit(X_train, y_train)
        preds_ridge = ridge_model.predict(X_test)
    
        plt.scatter(preds_ridge, y_test, alpha= 0.75, c= 'b')
        plt.xlabel('Predicted price')
        plt.ylabel('Actual price')
        plt.title('Ridge redularization with alpha {}'.format(alpha))
        overlay = 'R square: {} \nRMSE: {}'.format(ridge_model.score(X_test, y_test), mean_squared_error(y_test, preds_ridge))
        plt.annotate(s = overlay, xy = (12.1, 10.6), size = 'x-large')
        plt.show()
        
def actual_predict_visualization(actual_values, predict_values):
    plt.scatter(actual_values, predict_values, alpha= 0.75, color = 'b')

    plt.xlabel('Predicted price')
    plt.ylabel('Actual price')
    plt.title('Regression Model')
    plt.show()
    
def visualize_original_predict_test(X_val, Y_val, default = "Test"):
    print("Dataset type  : \n" ,default)
    plt.scatter(diabetes_X_test, diabetes_y_test,  color='black')
    plt.plot(diabetes_X_test, diabetes_y_pred, color='blue', linewidth=3)

    plt.xticks(())
    plt.yticks(())
    
    plt.xlabel("X axis", color = "red")
    plt.ylabel("Y axis", color = "green")

    plt.show()
    
    
def visualize_categorical_values(dataset):
    no_of_columns = 4
    no_of_rows = 4
    
    columns_object_type = [i for i in dataset.columns  if dataset[i].dtype == "object"]
    total_rows = (len(columns_object_type) // no_of_rows ) + 1
    
    f, axes = plt.subplots(total_rows, no_of_columns, figsize=(18,24))

    for ind, val in enumerate(columns_object_type):
        sns.countplot(df[val] , ax = axes[ind // no_of_rows , ind %no_of_columns ])
    plt.show()   
    
sns.pairplot(data = telecom_df[['arpu_6','arpu_7','arpu_8','churn_flag']],hue = 'churn_flag')

def visualize_pairplot_target(numberical_col_list , target_val):
    plt.figure(figsize=(18,34))
    sns.pairplot(data = telecom_df[numberical_col_list],hue = target_val)
    
    #     sns.pairplot(data = telecom_df[['arpu_6','arpu_7','arpu_8','churn_flag']],hue = 'churn_flag') 
    #check for classification
    plt.show()
    
    
def visualize_numberical_values(dataset):
    plt.figure(figsize=(18,34))
    sns.pairplot(df)
    plt.show()
# visualize_numberical_values(df)
    
def check_skewness_numerical(dataset, target):
    #analysing the distribution of sale price
    print('skew is', dataset.SalePrice.skew())   
    plt.hist(dataset[target], color= 'b')

    plt.title('Distribution of ' + target, fontsize = 24)
    plt.ylabel('observation', fontsize = 20)
    plt.xlabel(target, fontsize = 20)

    plt.show()
    
def skewness_after_log_transform(dataset , target):
    #log transforming sale price to transform it into gaussian distribution
    target1 = np.log(dataset.target)
    print('skew is', target1.skew())
    plt.hist(target, color= 'b')

    plt.title('Distribution of ' + target, fontsize = 24)
    plt.ylabel('observation', fontsize = 20)
    plt.xlabel(target , fontsize = 20)

    plt.show()
    
# Since pairplots for all numeric values together are not clear we can make groups ,do plot with price & analyse

def pair_plot(list_4_numberical_values):
    sns.pairplot(df2, x_vars= list_4_numberical_values, y_vars='SalePrice',size=4, kind='scatter')
    plt.show()

NameError: name 'telecom_df' is not defined

In [71]:
df.shape

(131662, 14)

In [72]:
# corr_2_more_visualize(df)

In [73]:
# visualize_categorical_values(df)

In [74]:
# visualize_numberical_values(df)

In [75]:
#Label encoding
def convert_to_numerical_datatype_train(dataset):
    enc = LabelEncoder()
    for i in dataset.columns:
        if(dataset[i].dtype == "object"):
            dataset[i] = enc.fit_transform(dataset[i])
            
    return dataset

In [76]:
class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0] if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)
    


# <font color ='green' > EDA

In [77]:
drop_col = ["Trip_ID" , "Var1"]

In [78]:
df1 = df.drop(columns = drop_col)
df.shape , df1.shape

((131662, 14), (131662, 12))

In [79]:
df1_test = df_test.drop(columns = drop_col)
df_test.shape , df1_test.shape

((87395, 13), (87395, 11))

In [80]:
df2= DataFrameImputer().fit_transform(df1)


df2_test = DataFrameImputer().fit_transform(df1_test)

In [81]:
df2.isna().sum().sum(), df2_test.isna().sum().sum()

(0, 0)

In [82]:
df3 = convert_to_numerical_datatype_train(df2)
df2.shape, df3.shape

((131662, 12), (131662, 12))

In [83]:
df3_test = convert_to_numerical_datatype_train(df2_test)
df2_test.shape, df3_test.shape

((87395, 11), (87395, 11))

In [84]:
def standardscaler_preprocessing(dataset_train, dataset_test, num_col):
    scaler = StandardScaler()
   
    dataset_train[num_col] = scaler.fit_transform(dataset_train[num_col])

    dataset_test[num_col] = scaler.transform(dataset_test[num_col])
    
    return dataset_train, dataset_test


In [85]:
scaling_col = ["Trip_Distance" , "Customer_Since_Months" , "Life_Style_Index", "Customer_Rating", "Var2", "Var3"]

In [86]:
df4, df4_test = standardscaler_preprocessing(df3, df3_test, scaling_col)

In [87]:
X = df4.iloc[:,:-1]

Y = df4.iloc[:,-1]

In [88]:
print( df["Trip_Distance"].max() , df["Trip_Distance"].min() , df["Trip_Distance"].mean())

print( df["Customer_Since_Months"].max() , df["Customer_Since_Months"].min() , df["Customer_Since_Months"].mean())

print( df["Life_Style_Index"].max() , df["Life_Style_Index"].min() , df["Life_Style_Index"].mean())

print( df["Customer_Rating"].max() , df["Customer_Rating"].min() , df["Customer_Rating"].mean())


109.23 0.31 44.20090853853045
10.0 0.0 6.016661099712109
4.87511 1.59638 2.8020639999461827
5.0 0.00125 2.849457958636489


In [89]:
X.head()

Trip_Distance  Type_of_Cab  Customer_Since_Months  Life_Style_Index  \
0      -1.466568            1              -1.415378     -1.801959e+00   
1      -0.577167            1               1.123841     -9.440728e-02   
2      -0.102689            1               1.123841      3.633778e-14   
3       0.680141            2               1.123841      3.633778e-14   
4       0.421157            2               1.123841      1.118919e+00   

   Confidence_Life_Style_Index  Destination_Type  Customer_Rating  \
0                            0                 0         1.076346   
1                            1                 0         0.612378   
2                            1                 4         0.664638   
3                            1                 0         0.616202   
4                            1                 0         0.563942   

   Cancellation_Last_1Month      Var2      Var3  Gender  
0                         0 -1.043456 -1.304086       0  
1                         0  0.962110  0.250555       1  
2                         2  0.962110  0.164186       1  
3                         0  0.159884 -0.094921       1  
4                         4 -0.441786  2.323410       1

In [90]:
def get_accuracy(y_train_val , y_pred_val , dataset_type = "Default"):
    
    print(" Dataset type is : ", dataset_type)
    
    print("\n Accuracy Score     : ",round(accuracy_score(y_train_val, y_pred_val), 4) * 100)
    
    print("\n precision_accuracy : ",round(precision_score(y_train_val, y_pred_val), 4) * 100)
 
    print("\n recall_accuracy    : ",round(recall_score(y_train_val, y_pred_val), 4) * 100)
    
    print("\n roc_auc_accuracy   : ",round(roc_auc_score(y_train_val, y_pred_val), 4) * 100)
    
    print("\n f1_score_accuracy  : ",round(f1_score(y_train_val, y_pred_val), 4) * 100)
    
    print("\n explained_variance  : ",round(explained_variance_score(y_train_val, y_pred_val), 4) * 100)
    
    tn, fp, fn, tp = confusion_matrix(y_train_val, y_pred_val).ravel()
    
    print("\n Confusion Matrix TN : ", tn, " FP : ", fp, " FN : ", fn, " TP : ", tp)

In [91]:

rows=[]

def addRandomStateForAlgorithm(x,y,names,algorithms,columns_name,random_state_list):    
    for j in range(len(algorithms)):
        model = algorithms[j]
        for i in random_state_list:
            
            x_train, x_test , y_train , y_test = train_test_split(x ,y , test_size = 0.30 , random_state = i)
            
            model.fit(x_train,y_train)
            
            y_pred_train = model.predict(x_train)
            y_pred = model.predict(x_test)
            
            train_acc = accuracy_score(y_train, y_pred_train)
            train_acc = round(train_acc, 4) * 100
            
            test_acc = accuracy_score(y_test, y_pred)
            test_acc = round(test_acc, 4) * 100
            
#             roc_auc_score_acc = roc_auc_score(y_test, y_pred)
#             roc_auc_score_acc = round(roc_auc_score_acc, 4) * 100
            

#             row = [names[j],   i,   train_acc, test_acc, roc_auc_score_acc]
            row = [names[j],   i,   train_acc, test_acc]
    
            rows.append(row)
            
    models_df = pd.DataFrame(rows) 
    
    models_df.columns = columns_name
    print(models_df)
    

In [92]:
   
# names_regression = [ "LightGBM", "RF", "XGBoost" , "SVM"]
# algorithms = [ LGBMClassifier(), RandomForestClassifier(), XGBClassifier(), SVC()]

# columns_name = ["Model",    "Random_state",   'Train_acc',     "Test_acc" , "roc_auc_score"]

names_regression = [ "XGBClassifier"]
algorithms = [ XGBClassifier(max_depth=5, objective='multi:softmax', num_classes=3)]

columns_name = ["Model",    "Random_state",   'Train_acc',     "Test_acc" ]


random_state_list_up_to_10 = [1]


addRandomStateForAlgorithm(X,Y,names_regression,algorithms,columns_name,random_state_list_up_to_10)

           Model  Random_state  Train_acc  Test_acc
0  XGBClassifier             1      69.48     68.88


In [93]:
# model_final = XGBClassifier(
#  learning_rate =0.1,
#  n_estimators=1000,
#  max_depth=5,
#  min_child_weight=1,
#  gamma=0,
#  subsample=0.8,
#  colsample_bytree=0.8,
#  objective= 'binary:logistic',
#  nthread=4,
#  scale_pos_weight=1,
#  seed=27)

model_final = XGBClassifier(max_depth=5, objective='multi:softmax', num_classes=3)


model_final.fit(X, Y)

y_pred_final = model_final.predict(df4_test)

In [94]:
submission_1 = submission.copy()

print(df_test.shape , submission.shape , len(y_pred_final))


(87395, 13) (87395, 2) 87395


In [95]:
submission_1["Surge_Pricing_Type"] = y_pred_final

print(submission_1["Surge_Pricing_Type"].values)

[1 2 2 ... 1 2 2]


In [96]:



submission_1.to_csv('submission_9_XGBoost_Sacle.csv', index=False)

df_submission_1 = pd.read_csv('submission_9_XGBoost_Sacle.csv')


In [97]:
print(df_submission_1.shape)

df_submission_1.head(3)

(87395, 2)


Trip_ID  Surge_Pricing_Type
0  T0005689459                   1
1  T0005689462                   2
2  T0005689463                   2

In [98]:
df.shape , df_test.shape

((131662, 14), (87395, 13))

In [99]:
131662 - 87395

44267

In [100]:
#train : train is a dataset

In [101]:
#Dataset : train & test


In [103]:
df.columns

Index(['Trip_ID', 'Trip_Distance', 'Type_of_Cab', 'Customer_Since_Months',
       'Life_Style_Index', 'Confidence_Life_Style_Index', 'Destination_Type',
       'Customer_Rating', 'Cancellation_Last_1Month', 'Var1', 'Var2', 'Var3',
       'Gender', 'Surge_Pricing_Type'],
      dtype='object')

In [104]:
Counter(df.Surge_Pricing_Type)

Counter({2: 56728, 3: 47720, 1: 27214})

In [109]:
df3[0:87395].shape  , df3[87395 : ].shape

((87395, 12), (44267, 12))

In [141]:
def majority_imbalanced_dataset(dataset, target_col):
    feature_columns = dataset.columns.tolist()
    feature_columns = [c for c in feature_columns if c not in [target_col]]

    X2 = dataset[feature_columns]
    Y2 = dataset[target_col]

    os =  RandomOverSampler(random_state=35)
    X_feature_variables , y_output = os.fit_sample(X2, Y2)
    
    return X_feature_variables , y_output

In [142]:
X_feature_variables1 , y_output1 = majority_imbalanced_dataset(df3, "Surge_Pricing_Type")

In [143]:
df10 = X_feature_variables1.copy()

In [145]:
df10["Surge_Pricing_Type"] = y_output1

In [146]:
df10.head()

Trip_Distance  Type_of_Cab  Customer_Since_Months  Life_Style_Index  \
0      -1.466568            1              -1.415378     -1.801959e+00   
1      -0.577167            1               1.123841     -9.440728e-02   
2      -0.102689            1               1.123841      3.633778e-14   
3       0.680141            2               1.123841      3.633778e-14   
4       0.421157            2               1.123841      1.118919e+00   

   Confidence_Life_Style_Index  Destination_Type  Customer_Rating  \
0                            0                 0         1.076346   
1                            1                 0         0.612378   
2                            1                 4         0.664638   
3                            1                 0         0.616202   
4                            1                 0         0.563942   

   Cancellation_Last_1Month      Var2      Var3  Gender  Surge_Pricing_Type  
0                         0 -1.043456 -1.304086       0                   2  
1                         0  0.962110  0.250555       1                   2  
2                         2  0.962110  0.164186       1                   2  
3                         0  0.159884 -0.094921       1                   3  
4                         4 -0.441786  2.323410       1                   2

In [148]:
df10.shape , df3.shape

((170184, 12), (131662, 12))

In [162]:
new_test = df10[0:87395]

new_train = df10[87395 : ] 

In [163]:
x1_train = new_train.iloc[:, :-1]
y1_train = new_train.iloc[:, -1]

In [164]:
x1_test = new_test.iloc[:, :-1]
y1_test = new_test.iloc[:, -1]

In [152]:
model_final = XGBClassifier(max_depth=5, objective='multi:softmax', num_classes=3)


model_final.fit(x1_train, y1_train)


y_pred_final_new_train = model_final.predict(x1_train)

# y_pred_final_new_test = model_final.predict(x1_test)

In [166]:
len(y1_test)

87395

In [167]:
y_pred_final_new_test = model_final.predict(df3_test)

In [ ]:
y_

In [154]:
get_accuracy(y1_train , y_pred_final_new_train ,  "Train")

 Dataset type is :  Train

 Accuracy Score     :  69.41000000000001
[[32209  3577  2880]
 [ 7132  7910  3973]
 [ 3632  4130 17346]]


In [156]:
get_accuracy(y1_test , y_pred_final_new_test ,  "Test")

 Dataset type is :  Test

 Accuracy Score     :  32.190000000000005
[[ 6722  4775  6565]
 [14185  9913 13615]
 [11743  8379 11498]]


In [137]:
get_accuracy(y1_test , y_pred_final_new_test ,  "Their Test")

 Dataset type is :  Their Test

 Accuracy Score     :  37.980000000000004
[[ 2570 10011  5481]
 [ 5323 21140 11250]
 [ 4447 17693  9480]]


In [157]:
def get_accuracy(y_train_val , y_pred_val , dataset_type = "Default"):
    
    print(" Dataset type is : ", dataset_type)
    
    print("\n Accuracy Score     : ",round(accuracy_score(y_train_val, y_pred_val), 4) * 100)
    
#     print("\n precision_accuracy : ",round(precision_score(y_train_val, y_pred_val), 4) * 100)
 
#     print("\n recall_accuracy    : ",round(recall_score(y_train_val, y_pred_val), 4) * 100)
    
#     print("\n roc_auc_accuracy   : ",round(roc_auc_score(y_train_val, y_pred_val), 4) * 100)
    
#     print("\n f1_score_accuracy  : ",round(f1_score(y_train_val, y_pred_val), 4) * 100)
    
#     print("\n explained_variance  : ",round(explained_variance_score(y_train_val, y_pred_val), 4) * 100)
    
#     tn, fp, fn, tp = confusion_matrix(y_train_val, y_pred_val).ravel()
    
#     print("\n Confusion Matrix TN : ", tn, " FP : ", fp, " FN : ", fn, " TP : ", tp)
    print(confusion_matrix(y_train_val, y_pred_val))

In [158]:
submission_new["Surge_Pricing_Type"] = y_pred_final_new_test


submission_new.to_csv('submission_new_imbalance.csv', index=False)


In [159]:
submission_new.shape , submission.shape

((87395, 2), (87395, 2))